name: Rust

on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Cargo clippy
              run: cargo clippy --all -- --verbose -D warnings

    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Cargo build
              run: cargo build --release --verbose

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run tests
              run: cargo test --verbose

    doc:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Check documentation
              run: RUSTDOCFLAGS="-D warnings" cargo doc --document-private-items --all --verbose --release

    fmt:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Check formatting
              run: cargo fmt -- --check

    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Restore cache
              uses: actions/cache/restore@v4
              with:
                  path: ~/.cargo/
                  key: cargo-cache
            - name: Install tarpaulin
              run: cargo install cargo-tarpaulin
            - name: Update cache
              uses: actions/cache/save@v4
              with:
                  path: ~/.cargo/
                  key: cargo-cache
            - name: Check coverage
              run: cargo tarpaulin --doc --tests  --fail-under 100
